name: Build and deploy TrustTree site to Azure Blob Storage
on:
  push:
    branches:
      - main #trigger the workflow on push request event for the master branch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Upload to Azure Blob Storage
         - uses: actions/checkout@v2
         - uses: bacongobbler/azure-blob-storage-upload@main
        with: 
          source_dir: public #gatsby build generates this file after build
          container_name: $web
          connection_string: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
